### ISSUE TITLE
400 Bad Request on Salesforce Token Endpoint

### ISSUE THREAD

**Issue by ghost** [TerribleDev/OwinOAuthProviders#177]
Whenever a post is being done to the token endpoint, e.g.:
  "https://**_.**_.force.com/services/oauth2/token"
in:
  AuthenticateCoreAsync()
in:
  SalesforceAuthenticationHandler the following error is returned:

...the following error comes back:
StatusCode: 400, ReasonPhrase: 'Bad Request'

When using postman to make a post with the same values to the same endpoint a response is being received.

**Comment by ghost** [comment]
The problem is resolved when adding this line:
ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12 | SecurityProtocolType.Tls11 | SecurityProtocolType.Tls;  

Above my:
"app.UseSalesforceAuthentication(options);" call.

My Salesforce environment is not accepting older TLS protocols anymore.
Hope this helps someone.

**Comment by benbenwilde** [comment]
I also had this problem. Same exact behavior. This [changed in July 2017](https://help.salesforce.com/articleView?id=000221207&type=1). 
@TerribleDev - It would be really nice to have a check for this in the Salesforce provider if possible to avoid future issues with this.

**Comment by TerribleDev** [comment]
@benbenwilde something like this? https://github.com/TerribleDev/OwinOAuthProviders/pull/206

**Comment by TerribleDev** [comment]
Except obviously for salesforce

**Comment by benbenwilde** [comment]
Unfortunately the response I got when I didn't have
`ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls | SecurityProtocolType.Tls11 | SecurityProtocolType.Tls12;` in place was `400 Bad Request` with this body:
```
{
    "error": "invalid_grant",
    "error_description": "authentication failure"
}
```

I can get the same response by having a bad code parameter as well, so I'm not sure the response is enough to diagnose the issue. Maybe there is a way to check the current SecurityProtocol setting, I don't know if just checking the property will work or not, and the default looks to be registry driven. Reference: https://stackoverflow.com/questions/28286086/default-securityprotocol-in-net-4-5

**Comment by TerribleDev** [comment]
Ahh, yes we'll probably have to check the enum for the correct bits. Would you like to submit a PR?, or should I just do it

**Comment by benbenwilde** [comment]
If you want that would be great. However I am concerned that there is some
magic around that enum because it's like if it doesn't get set, it just
uses a registry value or something.. I don't totally understand it. I'm
also concerned because it sounded like people tested their configuration
simply by making a request to some endpoint that detects and responds with
the security protocol you're using. Obviously we can't do that. Nonetheless
it would be really good to test the check if you do implement to make sure
we don't get false negatives/positives in case that value is inaccurate.

Also a more future proof fix would be to do something like
`.SecurityProtocolType |= .TLS11 | .TLS12`. This way, those two are added
without disabling any potential future better security protocols.

All of this being said, a code comment/warning on the `app.UseSalesforce()`
method summary might actually suffice if you think that there's no
reasonable way to implement an actual check right now. It's really too bad
that salesforce doesn't give a more useful error response.

**Comment by TerribleDev** [comment]
As a library, I I don't think the right thing to do is to change someone's tls settings without it being obvious.

Since enumerations can't be null I am going to assume that its hydrated with values from the registry. I'm travelling at the moment. When I am home I'll read sourceof.net and see how that enumeration is read and how it interacts with the registry. I'd prefer to not code like it were 'magic' as you describe, but to just figure out how to work with the behaviors.
