### ISSUE TITLE
Reversing dependency graph?

### ISSUE THREAD

**Issue by jeradrose** [TerribleDev/OwinOAuthProviders#190]
I recently updated my `Owin.Security.Providers` from 1.x to 2.x, and notice that it now depends on every single OWIN provider.

Is there any way to have it such that each of the individual providers can be optional, with each depending on `Owin.Security.Providers` instead of the other way around?

EDIT: Maybe I misunderstood the 2.0 changes, but maybe it's now possible to not even include the `Owin.Security.Providers` package, and just add the individual provider package?

**Comment by TerribleDev** [comment]
Well in the 1.x days every provider was baked into the 1 assembly so getting all 40ish providers as a meta provider is literally the same behavior as 1.x except that they are separate dll's now. So this is no different than before. 

I'm not sure what would be gained if they depended on the meta package. Since there is almost no code shared (open Id providers are the exception of course. )

Each package is already separate entity that can be added individually instead of the 1 huge meta package.

**Comment by TerribleDev** [comment]
Correct each package is self contained and do not require the meta package. That package is provided to allow you to have all the things if it's easier.

**Comment by TerribleDev** [comment]
We use the pay for play model now. So just import the packages you wish to use and no more.

**Comment by TerribleDev** [comment]
@jeradrose you all set? I'm going to close this issue feel free to reopen if I didn't understand your question fully.

**Comment by jeradrose** [comment]
@TerribleDev thanks so much for the info, all makes sense now.
