### ISSUE TITLE
PayPal requires TLS1.2

### ISSUE THREAD

**Issue by bencurthoys** [TerribleDev/OwinOAuthProviders#205]
To get the PayPal Authentication working in the sandbox, I had to add 

    System.Net.ServicePointManager.SecurityProtocol = System.Net.SecurityProtocolType.Tls12;

to the PayPalAuthenticationHandler because http://stackoverflow.com/questions/34939523/the-request-was-aborted-could-not-create-ssl-tls-secure-channel-sandbox-account.

Plus it would have saved me time if if Startup.Auth.cs in the Demo included a comment saying

    // Return URL must be configured in the PayPal application to https://[hostname][:port]/signin-paypal

because otherwise there's nothing to tell you that's what it should be. 

Would you like me to create a Pull request with these changes in it, or is it easier if you do it?

**Comment by TerribleDev** [comment]
My concern about that change is that it will affect processes outside of this dll. In that, since that is a static won't it set that behavior for other users code?

**Comment by bencurthoys** [comment]
Good point. Perhaps it should go in the demo code rather than the DLL then? Either way, without that set somehow, I believe that it won't work in the sandbox now and will stop working on live on June 17.

**Comment by TerribleDev** [comment]
That's a tough situation. I'd say add it to the demo, and even add a small header at the bottom of the readme. I'm not sure implementing this in our dll is the smartest thing. For instance what if someone wants to use 1.3 instead of 1.2

The more I think about this issue, the more I think just documenting the problem is the best result. Wanna fire off a PR updating the comments and maybe adding a quick note in the readme?

**Comment by bencurthoys** [comment]
Ok. Done that. Apologies if I've cocked anything up; I don't normally use Git.
