### ISSUE TITLE
Provide separate NuGet packages

### ISSUE THREAD

**Issue by hazzik** [TerribleDev/OwinOAuthProviders#51]
It will be handy to have a separate nuget package for each provider

**Comment by jerriep** [comment]
Yes! But right now the future of this project is a bit in doubt seeing as MS is building a very generic OAuth provider for ASP.NET 5 which will make most of these providers redundant. As soon as I have a clearer view on how to proceed going forward this is definitely under consideration. I have had this request many times...

**Comment by hazzik** [comment]
Do you have a link about this generic provider?\* Now there is a DotNetOpenAuth (DNOA) project which makes OAuth/2/OpenId integration easy as 1-2-3 (you basically need to specify only endpoints and make a final request for user info). But as I know (I may be wrong) that there is currently no OWIN integration for DNOA

**Comment by hazzik** [comment]
<s>\* As I can see [here](https://github.com/aspnet/Security/tree/dev/src) AspNet team do exactly the same as your provider, so no further generalization. </s>
Ah, I see it here https://github.com/aspnet/Security/tree/dev/src/Microsoft.AspNet.Security.OAuth

**Comment by jerriep** [comment]
Yeah, the new one from the Aspnet team is the same - you just specify the endpoints. See this file for example configurations:

https://github.com/aspnet/Security/blob/dev/samples/SocialSample/Startup.cs

**Comment by AlexArchive** [comment]
I want this too.

Even when stable Asp 5 is released developers will still be using 4.5 for some time (or so I think).

Each package could have its own version number (semmantic version) and release notes which will be nice. I would implement #59 then.

If I can find a way to manage 10+ packages easily then I'll _probably_ do it.

**Comment by TerribleDev** [comment]
You could setup some rake tasks (or cake if you don't like ruby) with something like appveyor to build/deploy on every merge into master.

**Comment by AlexArchive** [comment]
I'll look into it. Thanks, @tparnell8.

**Comment by Eonasdan** [comment]
You could easily create separate nuspec files and either use a batch file or a grunt task to build to the packages. I'm not sure about automatically publishing the packages, but separating the providers should be relatively easy.

**Comment by TerribleDev** [comment]
Appveyor will auto pack and can even auto publish nuget packages

**Comment by jerriep** [comment]
I don't have the time or energy to "easily" separate the nuspec files. Unfortunately I also have very little time to spend on this project anymore.

If one of you want to step up and take over please speak up. You can then also do with the nuget packages are you please, as this project then becomes your responsibility.

**Comment by Eonasdan** [comment]
and...... done https://github.com/eonasdan/OwinOAuthProviders

**Comment by jerriep** [comment]
@Eonasdan I am totally confused by what you have done now.... ? You created a complete copy of the repo, so where do people actually go when they now want to make contributions? To your repo, or to mine?

What I said is that if you wanted to do this then you need to _take over_ the project. Not create a copy of it.

This means I need to transfer this repo to you. And I need to transfer the original NuGet package to you.

If you're searious about this, let's do this properly because all you have done now in my opinion is create confusion

**Comment by jerriep** [comment]
@Eonasdan Also what you have done now is create a new copy of the project without any reference to the original project. Also not contributing back to the original project.

I am honestly not sure whether what you have done is even legal under the MIT license.

Please let us do this properly. When you want to do something you discuss it with people.

**Comment by TerribleDev** [comment]
@jerriep I don't want to step on anyone's toes including @Eonasdan's, but I'd like to take ownership of this Repo.

I have contributed multiple providers to this project, and have even spent the time porting some providers over to the [aspnet contrib](https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers) project. I'd like to see these providers remain on MIT, and mostly kept around for the .NET 4.x./owin programming model. I know some Early stage companies that took deps on this repo, and I'd like to make sure the quality remains high. 

I think in the past we have chatted on gitter, and could probably migrate ownership with ease.

**Comment by jerriep** [comment]
Sure thing @tparnell8, I will appreciate that

I do not mind what @Eonasdan did, but the way it is done is wrong. Those changes should happen in **this** repo, because making a copy of it is not going to work. I can transfer ownership to you. And then if you can somehow replay his changes on this repo it would be great

Please let me know you Nuget username as well so I can transfer the packages

I appreciate your stepping up!

**Comment by TerribleDev** [comment]
@jerriep https://www.nuget.org/profiles/tparnell tparnell

**Comment by TerribleDev** [comment]
@jerriep I'll make sure his changes get in...fire off the xfer request at your leisure

**Comment by jerriep** [comment]
Should this repo be transferred to you personal GH account, or do you have an GH org I should transfer it to?

**Comment by TerribleDev** [comment]
@jerriep personal for now is fine..thanks!

**Comment by jerriep** [comment]
Cool will do it later today. Thank you!

**Comment by Eonasdan** [comment]
I didn't publish the nuget packages because I want to see what the response was. I'm happy to push the changes into this repo. I attempted to fix some issues with the github repo where you expressed that you have much time for this project, something I'm all to familiar with myself, so I didn't know if you'd be interested in a merge.

If @tparnell8 wants some help I don't mind sticking around. Mostly, I was bored this weekend and wanted to see if I could write a console app to do the split (which I did).

Despite the increased complexity of the Solution, I think it actually more maintainable this way.

**Comment by jerriep** [comment]
I appreciate what you did @Eonasdan it is just that if you create a copy of the repo and do it there it helps no-one. 

@tparnell8 is taking this over and I am grateful for that. And he will get those changes if yours merged.

**Comment by Eonasdan** [comment]
done

**Comment by jerriep** [comment]
@tparnell8 You will need to delete your fork otherwise I cannot transfer you you because you already have a repo with that same name

**Comment by TerribleDev** [comment]
@jerriep good call...and done!

**Comment by TerribleDev** [comment]
@jerriep looks like it xfer'd :confetti_ball:

**Comment by jerriep** [comment]
Yep, all yours now haha

**Comment by TerribleDev** [comment]
:+1:
