### ISSUE TITLE
Support Playstation Network OAuth (PSN)

### ISSUE THREAD

**Issue by markadrake** [TerribleDev/OwinOAuthProviders#62]
I'll try to tackle this myself by looking at the other providers as an example. However, I couldn't find any documentation on integrating an OAuth login with PSN. The best thing I've found is actually here on GitHub (https://github.com/jhewt/gumer-psn/blob/master/psn.js). 

To me, it looks like the server is imitating another site to get access to an API that I suppose is not public and not meant to be used in this way. If that's the case, I'm not sure how interested I am in doing this. I feel that imitating another server leads to a lot of ethical concerns I don't want associated with my site nor do I want to expose my users to - especially the negative potential effects of violating a TOS agreement. 

Hence why I'm posting this I guess - has anyone explored trying to integrate with Playstation Network / Xbox Live and made any progress at all? Thanks!

**Comment by AlexArchive** [comment]
Hm. It looks like the author of [gumber-psn](https://github.com/jhewt/gumer-psn) monitored the Android app's requests in order to emulate them to access the private web API. It does not look like Playstation Network have an official web API. ([And I know from experience Xbox Live do not.](https://github.com/ByteBlast/Durango))

I do not think this will work very well for the reasons you described. Additionally: 
1. There is no documentation
2. The API is not guaranteed to be stable (if we took this on and Sony changed the Api internally or deprecated it, we would be in trouble.)
3. I doubt Sony have a Web UI for OAuth?

[With Durango I emulated the browser requests](https://github.com/ByteBlast/Durango/blob/master/Durango/Authentication/StandardAuthenticator.cs). But I know services such as [Xbox API](https://xboxapi.com/) access the same private API the Android application uses. I remember that [one implementation in PHP](https://github.com/XboxLeaders/XboxLiveAPI) rotated accounts - so I know there's a possibility of being banned for violating the TOS.

If you want to do this for your own use _anyway_ then by all means do and tell me how it goes. I do not want you spend a lot of time on this for the sole purpose of having it here and have me turn down the contribution because of the issues outlined here. I really appreciate your interest though.

Please let me know what you decide to do :bear:.

**Comment by markadrake** [comment]
@ByteBlast Thanks for your quick reply and confirming I was on the right track. I think right now it's best to avoid using this seemingly sneaky way to access an API. It will only (1) confuse our users down the road, (2) put us on blast when a breaking change occurs, and at the very worst (3) cause TOS violations. I'm developing a video game coverage site - so this project has been extremely helpful as I was able to integrate with various log-in services (big thanks for Twitch).

I'm going to avoid doing the work - at least until it is clearly defined by Sony that this is okay or not okay. Trying to get my questions to the right people over there for an official response. 

Thanks mate!

**Comment by AlexArchive** [comment]
All good mate. I am glad you like the project - I think it was @tparnell8 who implemented the Twitch provider - I'm sure he'll be pleased to hear about you benefiting from his contribution. 

I'll close this issue for now. But if you learn something through speaking with Sony, please do not hesitate to start the discussion again.

**Comment by TerribleDev** [comment]
@markusdrake glad to hear you are enjoying the twith OAuth. 

Thanks for the shoutout @ByteBlast
